### PR TITLE
adds support for anonymous secrets POST from the WebUI

### PR DESCRIPTION
**Pull request by nii236**
This pull request adds a form that lets anonymous users POST secrets.

It adds a new flag that lets you opt-in to the feature, `-allow-anonymous`.

### CODE REVIEW

**Comment by sstark** [comment]
Thanks a lot for your contribution! There are some issues with it:

- You are creating a new URL ("/api/v1/create"), which is good. But I would rather not make it part of the api, because it is not using json for input/output. I would find it better if it was just "/create" instead.
- A really minor issue: the submission form is rendered in black when I try it with firefox. Chromium looks ok. Maybe something can be added to the css to make it look better.
- In its current form, your patch will make gjfy accept anonymous posts even if the -allow-anonymous flags is not set (you are just toggleing the display of the form on and off). I think the easiest way to fix it would be to put the whole `http.HandleFunc(uApiCreate...` inside an `if fAllowAnonymous {...` block.

Would you mind looking into these? You can either add more commits to your branch or force push a new commit to it, whatever you prefer.

**Comment by nii236** [comment]
Thanks for your response @sstark! I've implemented what you have asked, hopefully to your satisfaction.

**Comment by sstark** [comment]
Sorry for answering late. Looks better now thanks. Just now with those new commits some things sneaked in that shouldn't be part of this PR: `.gitignore`, `go.mod`, `go.sum`. The go mod thing could be another, separate PR. Could you maybe change the commit (not add on top this time) to not contain those?

**Comment by nii236** [comment]
No problem @sstark. Does it satisfy you now?

**Comment by sstark** [comment]
@nii236  Thanks for your patch!

**Pull request merged**
